-- WARNUNG: DIESES SKRIPT LÖSCHT ALLE DATEN IN DEN TABELLEN!
-- Es setzt die Datenbank komplett zurück auf den Stand, den der Code benötigt.

-- 1. ALTE TABELLEN LÖSCHEN (Drop Tables)
DROP TABLE IF EXISTS public.logs CASCADE;
DROP TABLE IF EXISTS public.workout_exercises CASCADE;
DROP TABLE IF EXISTS public.workouts CASCADE;

-- 2. TABELLEN NEU ANLEGEN (Clean Schema)

-- Tabelle: WORKOUTS
CREATE TABLE public.workouts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    name TEXT NOT NULL,
    user_id UUID REFERENCES auth.users NOT NULL, -- Jetzt direkt NOT NULL, da Tabelle leer
    is_template BOOLEAN DEFAULT false,
    routine_name TEXT DEFAULT 'EINZELNE_WORKOUTS'
);

-- Tabelle: WORKOUT_EXERCISES
CREATE TABLE public.workout_exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id UUID REFERENCES public.workouts(id) ON DELETE CASCADE,
    exercise TEXT NOT NULL,
    sets INTEGER DEFAULT 3,
    reps INTEGER,
    rest_time INTEGER DEFAULT 60,
    is_cardio BOOLEAN DEFAULT false
);

-- Tabelle: LOGS
CREATE TABLE public.logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    user_id UUID REFERENCES auth.users NOT NULL,
    date DATE NOT NULL,
    workout UUID, 
    workout_name TEXT,
    exercise TEXT NOT NULL,
    set INTEGER NOT NULL,
    weight NUMERIC,
    reps NUMERIC,
    duration NUMERIC,
    calories NUMERIC,
    is_cardio BOOLEAN DEFAULT false
);

-- 3. SICHERHEIT (RLS) EINRICHTEN

-- Aktivieren
ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workout_exercises ENABLE ROW LEVEL SECURITY;

-- --- LOGS POLICIES ---
CREATE POLICY "User sees own logs" ON public.logs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "User inserts own logs" ON public.logs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "User deletes own logs" ON public.logs FOR DELETE USING (auth.uid() = user_id);

-- --- WORKOUTS POLICIES ---
CREATE POLICY "User sees own workouts and templates" ON public.workouts FOR SELECT USING (auth.uid() = user_id OR is_template = true);
CREATE POLICY "User manages own workouts" ON public.workouts FOR ALL USING (auth.uid() = user_id);

-- --- WORKOUT_EXERCISES POLICIES ---
CREATE POLICY "Access own workout exercises" ON public.workout_exercises
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.workouts w
    WHERE w.id = workout_exercises.workout_id
    AND (w.user_id = auth.uid() OR w.is_template = true)
  )
);
