-- RESTORE SCRIPT FOR FITNESS APP (Commit b0b0d8c)
-- Dieses Skript ist "idempotent" - es repariert fehlende Spalten und Policies, egal in welchem Zustand die DB ist.

-- 1. TABELLEN PRÜFEN & SPALTEN ERGÄNZEN

-- Tabelle: WORKOUTS
CREATE TABLE IF NOT EXISTS public.workouts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    name TEXT NOT NULL
);

-- Sicherstellen, dass user_id existiert (Kritischer Fehler-Fix)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'workouts' AND column_name = 'user_id') THEN
        ALTER TABLE public.workouts ADD COLUMN user_id UUID REFERENCES auth.users NOT NULL;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'workouts' AND column_name = 'is_template') THEN
        ALTER TABLE public.workouts ADD COLUMN is_template BOOLEAN DEFAULT false;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'workouts' AND column_name = 'routine_name') THEN
        ALTER TABLE public.workouts ADD COLUMN routine_name TEXT DEFAULT 'EINZELNE_WORKOUTS';
    END IF;
END $$;


-- Tabelle: WORKOUT_EXERCISES
CREATE TABLE IF NOT EXISTS public.workout_exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id UUID REFERENCES public.workouts(id) ON DELETE CASCADE,
    exercise TEXT NOT NULL
);

-- Migration Apply & Spalten-Check
DO $$
BEGIN
    -- Rename reps_max -> reps falls nötig
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'workout_exercises' AND column_name = 'reps_max') THEN
        ALTER TABLE public.workout_exercises RENAME COLUMN reps_max TO reps;
    END IF;

    -- Add columns if missing
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'workout_exercises' AND column_name = 'sets') THEN
        ALTER TABLE public.workout_exercises ADD COLUMN sets INTEGER DEFAULT 3;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'workout_exercises' AND column_name = 'reps') THEN
        ALTER TABLE public.workout_exercises ADD COLUMN reps INTEGER;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'workout_exercises' AND column_name = 'rest_time') THEN
        ALTER TABLE public.workout_exercises ADD COLUMN rest_time INTEGER DEFAULT 60;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'workout_exercises' AND column_name = 'is_cardio') THEN
        ALTER TABLE public.workout_exercises ADD COLUMN is_cardio BOOLEAN DEFAULT false;
    END IF;
END $$;


-- Tabelle: LOGS
CREATE TABLE IF NOT EXISTS public.logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    date DATE NOT NULL,
    exercise TEXT NOT NULL,
    set INTEGER NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'logs' AND column_name = 'user_id') THEN
        ALTER TABLE public.logs ADD COLUMN user_id UUID REFERENCES auth.users NOT NULL;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'logs' AND column_name = 'workout') THEN
        ALTER TABLE public.logs ADD COLUMN workout UUID;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'logs' AND column_name = 'workout_name') THEN
        ALTER TABLE public.logs ADD COLUMN workout_name TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'logs' AND column_name = 'weight') THEN
        ALTER TABLE public.logs ADD COLUMN weight NUMERIC;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'logs' AND column_name = 'reps') THEN
        ALTER TABLE public.logs ADD COLUMN reps NUMERIC;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'logs' AND column_name = 'duration') THEN
        ALTER TABLE public.logs ADD COLUMN duration NUMERIC;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'logs' AND column_name = 'calories') THEN
        ALTER TABLE public.logs ADD COLUMN calories NUMERIC;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'logs' AND column_name = 'is_cardio') THEN
        ALTER TABLE public.logs ADD COLUMN is_cardio BOOLEAN DEFAULT false;
    END IF;
END $$;


-- 2. SICHERHEIT (RLS) - ERNEUERUNG

ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workout_exercises ENABLE ROW LEVEL SECURITY;

-- Aufräumen alter Policies
DROP POLICY IF EXISTS "User sees own logs" ON public.logs;
DROP POLICY IF EXISTS "User inserts own logs" ON public.logs;
DROP POLICY IF EXISTS "User deletes own logs" ON public.logs;

DROP POLICY IF EXISTS "User sees own workouts and templates" ON public.workouts;
DROP POLICY IF EXISTS "User manages own workouts" ON public.workouts;

DROP POLICY IF EXISTS "Access own workout exercises" ON public.workout_exercises;
DROP POLICY IF EXISTS "User manages exercises via workout" ON public.workout_exercises;
DROP POLICY IF EXISTS "Einsicht in Übungen erlaubter Pläne" ON public.workout_exercises;


-- --- LOGS POLICIES ---
CREATE POLICY "User sees own logs" ON public.logs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "User inserts own logs" ON public.logs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "User deletes own logs" ON public.logs FOR DELETE USING (auth.uid() = user_id);

-- --- WORKOUTS POLICIES ---
CREATE POLICY "User sees own workouts and templates" ON public.workouts FOR SELECT USING (auth.uid() = user_id OR is_template = true);
CREATE POLICY "User manages own workouts" ON public.workouts FOR ALL USING (auth.uid() = user_id);

-- --- WORKOUT_EXERCISES POLICIES ---
CREATE POLICY "Access own workout exercises" ON public.workout_exercises
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.workouts w
    WHERE w.id = workout_exercises.workout_id
    AND (w.user_id = auth.uid() OR w.is_template = true)
  )
);
